# Generated by Django 4.0.2 on 2022-03-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0002_receita_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
    ]
