# Generated by Django 4.0.2 on 2022-03-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0007_alter_receita_foto_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='foto_receita',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
